accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView, logout

from accounts.views import registeration

urlpatterns = [

    url(r'^login/', LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),
    url(r'^register/', registeration, name='register'),
]

beta2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^pub/', include('public.urls', namespace='public')),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^', include('education.urls', namespace='edu')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

education/urls.py
from django.conf.urls import url, include
from education import school_dashboard_views as school_views
from education import student_dashboard_views as student_views
from education import views



student_urlpattern=[

    url(r'^$', student_views.StudentCourses.as_view(), name='signed_home'),
    url(r'^(?P<student_code>\w+)/$', student_views.StudentAllCoursesState.as_view(), name='student_all_courses_state'),
    url(r'^course/(?P<course_pk>\d+)/(?P<student_code>\w+)/report/', student_views.StudentCourseReport.as_view(),name='student_course_report'),
    url(r'^course/(?P<course_pk>\d+)$', student_views.CourseViewForParticipant.as_view(), name='course_dashboard_participant'),
]

school_urlpattern=[
    url(r'^course/(?P<course_pk>\d+)/add/$', school_views.AddingStudentView.as_view(), name='adding_student'),
    url(r'^course/(?P<course_pk>\d+)/exam/(?P<exam_pk>\d+)/$', school_views.SchoolExamDashboardView.as_view(), name='exam_detail'),
    url(r'^course/(?P<course_pk>\d+)/$', school_views.CourseViewForSchool.as_view(), name='course_dashboard'),



#form POST urls not GET
    url(r'^course/(?P<course_pk>\d+)/take/$', school_views.take_attend, name='take_attend'),
    url(r'^course/(?P<course_pk>\d+)/exam/create/$', school_views.create_exam, name='create_exam'),
    url(r'^course/(?P<course_pk>\d+)/exam/(?P<exam_pk>\d+)/create/$', school_views.create_exam_record, name='create_exam_record'),

#api tests not for production
    url(r'^course/(?P<course_pk>\d+)/(?P<student_code>\w+)/json/', student_views.AttendanceJsonView.as_view(),name='student_attend_json'),
    url(r'^course/(?P<student_code>\w+)/json/', student_views.StudentCoursesAttendancesJsonView.as_view(),name='student_attend_json'),

]
general_urlpattern=[
    url(r'^template/$', views.Template.as_view(), name='template'),
    url(r'^student/create/$', views.UserCreateStudentView.as_view(), name='create_student'),
    url(r'^$', views.AllCoursesList.as_view(), name='not_signed_home'),
    
    #Student Report for specific course both student , school and parents can access
    url(r'^course/(?P<course_pk>\d+)/(?P<student_code>\w+)/', views.StudentCourseInfoView.as_view(),name='student_course_info'),

]

urlpatterns= [
url(r'st/',include(student_urlpattern)),
url(r'sc/',include(school_urlpattern)),
url(r'',include(general_urlpattern)),
]

education/models.py
from django.contrib.auth.models import User
from django.db.models.signals import post_save, m2m_changed

from django.dispatch import receiver
from django.db import models
import random, string, time
# Create your models here.
from django.urls import reverse
from .managers import ExamRecordManager

codes=[]
def id_generator(size=5, chars=string.ascii_uppercase + 4*string.digits):
    x= (''.join(random.choice(chars) for i in range(size)))
    if codes.__contains__(x):
        return id_generator()
    codes.append(x)
    return x



class Student(models.Model):
    user = models.OneToOneField(User)
    study_at=models.CharField(max_length=70, null=True, blank=True)
    code = models.CharField(db_index=True, max_length=5, null=False, primary_key=True, default=id_generator)



    def __str__(self):
        return self.user.username


class School(models.Model):
    user=models.OneToOneField(User)
    Name=models.CharField(max_length=50, null=False)
    adress=models.TextField(max_length=120)
    photo=models.ImageField(blank=True)
    bio=models.TextField(max_length=500)
    slug=models.SlugField(max_length=20)

    class Meta:
        permissions = (
            ("add_students", "Can add new students"),
            ("edit_course", "Can change the information of course"),
            ("delete_student", "Can remove a student by setting its status as closed"),
        )
    def __str__(self):
        return self.Name

class Course(models.Model):
    years=(
        ('a', 'اولي اعدادي'),
        ('b', 'ثانية اعدادي'),
        ('c', 'ثالتة اعدادي'),
        ('d', 'اولي ثانوي'),
        ('e', 'ثانية ثانوي'),
        ('f', 'ثالثة ثانوي'),
        ('g', 'اخري'),
    )
    name=models.CharField(max_length=50, null=False)
    photo = models.ImageField(blank=True)
    groups=models.TextField(null=True)
    school=models.ForeignKey(School)
    year=models.CharField(max_length=30,choices=years)
    student=models.ManyToManyField(Student , related_name='courses')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('edu:course_dashboard', args=[self.id])


class Exam(models.Model):
    course=models.ForeignKey(Course, related_name='exams')
    name=models.CharField(max_length=60, null=True, blank=True)
    exam_time=models.DateTimeField(db_index=True, auto_now_add=True,auto_now=False, editable=True)
    max_mark=models.FloatField()

    def get_absolute_url(self):
        return reverse('edu:exam_detail', args=[self.course.id ,self.id])

    def __str__(self):
        if self.name:
            return self.name
        return 'Exam of course '+str(self.course.name)+' at time '+(self.exam_time).strftime('%A,  %I:%M %p, %d, %B')

class ExamRecord(models.Model):
    exam=models.ForeignKey(Exam, related_name='examrecords')
    exam_time=models.DateTimeField(db_index=True, auto_now_add=True,auto_now=False, editable=True)
    student_degree=models.FloatField(db_index=True,)
    student=models.ForeignKey(Student, related_name='examrecords')

    objects=ExamRecordManager()

    class Meta:
        unique_together=['exam', 'student']

    def __str__(self):
        return str(self.student) +' got ' +str(self.student_degree) + ' on Exam' +' from '+str(self.exam.max_mark)

class AttendanceRecord(models.Model):
    course=models.ForeignKey(Course, related_name='attendances')
    student = models.ForeignKey(Student, related_name='attendances')
    attend_time=models.DateTimeField(db_index=True, auto_now_add=True,auto_now=False, editable=True)
    update=models.DateTimeField(auto_now_add=False,auto_now=True, editable=True)


    def __str__(self):
        return (self.attend_time).strftime('%A,  %I:%M %p, %d, %B') + '  ' +str( self.student)


class Notification(models.Model):
    course=models.ForeignKey(Course ,related_name='notifications')
    text=models.CharField(max_length=300)
    time_stamp=models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now_add=False, auto_now=True, editable=True)

    def __str__(self):
        return self.text


class Question(models.Model):
    course=models.ForeignKey(Course, related_name='questions')
    title=models.CharField(max_length=150)
    description=models.TextField( null=True, blank=True)
    image=models.ImageField(blank=True, null=True)
    time_stamp=models.DateTimeField(auto_now_add=True)
    update=models.DateTimeField(auto_now_add=False, auto_now=True)
    asker=models.ForeignKey(Student, related_name='questions')
    def __str__(self):

        return self.title


class Reply(models.Model):
    question=models.ForeignKey(Question, related_name='replies')
    text=models.TextField()
    image=models.ImageField(null=True, blank=True)
    replier=models.ForeignKey(Student, related_name='replies')
    likes=models.PositiveIntegerField(default=0, blank=True)

    def __str__(self):
        return self.text

class StudentReport(models.Model):
    course=models.ForeignKey(Course, related_name='reports')
    student=models.ForeignKey(Student, related_name='reports')
    exams=models.ManyToManyField(Exam, blank=True)
    examrecords=models.ManyToManyField(ExamRecord, blank=True)
    attendances=models.ManyToManyField(AttendanceRecord, blank=True)
    total_student_degrees=models.PositiveIntegerField(blank=True, default=0, null=True)
    total_max_exam_degrees=models.PositiveIntegerField(blank=True, default=0, null=True)
    total_attendance_score=models.PositiveIntegerField(blank=True, default=0, null=True)

    class Meta:
        unique_together=['course', 'student']

    def __str__(self):
        return 'Report of Student: ' + str(self.student)


def update_report_exams(sender, instance, **kwargs):
    exams=instance.exams.filter(course=instance.course)
    total_exams=0
    for exam in exams:
        total_exams+=exam.max_mark

    instance.total_max_exam_degrees=total_exams
    instance.save()



def update_report_examrecords(sender, instance, **kwargs):
    exam_set=instance.exams.all()
    examrecords=instance.examrecords.filter(student=instance.student, exam__in=exam_set)
    total_student=0
    for record in examrecords:
        total_student+=record.student_degree
    instance.total_student_degrees = total_student
    instance.save()

def update_report_attendances(sender, instance, **kwargs):
    instance.total_attendance_score=instance.attendances.filter(student=instance.student).count()
    instance.save()





m2m_changed.connect(update_report_exams, sender=StudentReport.exams.through)
m2m_changed.connect(update_report_examrecords, sender=StudentReport.examrecords.through)
m2m_changed.connect(update_report_attendances, sender=StudentReport.attendances.through)

education/forms.py
from django import forms

from education.models import Course, Student, AttendanceRecord, Exam, ExamRecord


class AddingStudentForm(forms.ModelForm):

    class Meta:
        model= Course
        fields=['student']


class CreateStudentForm(forms.ModelForm):

    class Meta:
        model= Student
        fields=['study_at', 'code']


class TakeAttendForm(forms.ModelForm):
	"""docstring for TakeAttendForm"""
	code=forms.CharField()
	class Meta:
		model= AttendanceRecord
		fields = ["code"]

class CreateExamForm(forms.ModelForm):
    """docstring for ClassName"""
    class Meta:
        model=Exam
        fields=['name','max_mark']

class ExamRecordForm(forms.ModelForm):

    code=forms.CharField()

    class Meta:
        model=ExamRecord
        fields=['code','student_degree']


class AttendanceFilterForm(forms.Form):
    From=forms.DateTimeField()
    To=forms.DateTimeField()
    

education/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
import datetime
from django.db.models import Max, Sum, Count, Q
from django.http import JsonResponse
# Create your views here.
#from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, FormView, DetailView, CreateView, View

from education.forms import AddingStudentForm, CreateStudentForm, TakeAttendForm, ExamRecordForm, CreateExamForm,AttendanceFilterForm
from education.mixins import  TeacherCannotSeeOtherCoursesDashboardMixin
from education.models import Course, Student, AttendanceRecord, Exam, ExamRecord, Question,Notification,StudentReport

class Template(TemplateView):
    template_name='testo.html'


class AllCoursesList(ListView):
    model = Course
    template_name = 'edu_index_not_signed.html'
    context_object_name = 'courses'


class UserCreateStudentView(CreateView):
    form_class = CreateStudentForm
    template_name = 'create_student.html'
    success_url = reverse_lazy('edu:signed_home')
    def form_valid(self, form):
        form.instance.user=self.request.user
        return super(UserCreateStudentView, self).form_valid(form)



class StudentCourseInfoView(TemplateView):

    template_name = 'student_course_info.html'
    def get_context_data(self, **kwargs):

        context=super().get_context_data(**kwargs)
        context['course']=course=get_object_or_404(Course, pk=self.kwargs['course_pk'])
        context['student']=student = get_object_or_404(Student, code=self.kwargs['student_code'])
        context['attendances']=AttendanceRecord.objects.filter(course=course, student=student)
        context['exams']=exams=Exam.objects.filter(course=course)
        context['records']=ExamRecord.objects.filter(student=student).filter(
            exam__course=course)
        return context

education/templates/adding_student.html
{% extends 'base.html'%}
{% block body %}

<form method="post">
    {% csrf_token%}
    {{ form.as_p }}
    <button type="submit" class="btn btn-danger">Add Student</button>
</form>


{% endblock %}

education/templates/create_student.html
{% extends 'base.html' %}

{% block body %}
<br>

{% if  request.user.is_authenticated %}
<div class="container mt-2">
    <h4>Complete your info to become a student on Rafeki</h4>
<form method="post">
{% csrf_token %}
{{ form.as_p }}
<button type="submit">Become a Student</button>
</form>
</div>
{% else %}
    <h3>Please Login First <a href="{% url 'accounts:login'%}">login</a></h3>
{%endif%}
{% endblock %}

education/templates/edu_index_not_signed.html
{% extends 'base.html'%}
{% block body %}


<div class="courselist">

<div class="row">
{% for course in courses%}
<div class="col-4 offset-md-1  mt-5">
{% include "snippets/course_card.html" with title=course.name school=course.school url=course.get_absolute_url %}
</div>
{% endfor %}
</div>
</div>
{% endblock %}

education/templates/edu_index_signed.html
{% extends 'base.html'%}

{% load education_filters %}
{% block body %}

{% if not courses %}
<div class="container">
<div class="row">
<div class="col-6 mx-auto">
<h1 class="mt-5 ml-5" style="color: #dd2d41"> Code: {{ request.user.student.code }}</h1>
    <h4>This is your Code, share it with your Teachers and School to join you. Also share it with your family</h4>
    <br></br>
    <h4>Opps you are not a member of any course... You can see all our courses <a href="{%url 'edu:not_signed_home'%}">here</a></h4>
</div>
</div>
</div>
{% else%}
<div class="row">
{% block signed %}
{% for course in courses%}
{% student_course_exams_progress request.user.student course as exam_progress %}
<div class="col-4 offset-md-1  mt-5">
{% include "snippets/course_card.html" with title=course.name school=course.school url=course.get_absolute_url  student_degrees=exam_progress.student exams_degrees=exam_progress.exams precentage=exam_progress.precentage %}
</div>

{% endfor %}

</div>

{%endblock signed%}
{%endif%}
{% endblock body %}

education/templates/participant_course_view.html
{% extends 'base.html'%}
{% block title%}
{{course.name }} Page
{% endblock %}
{% block body %}
<div class="container">
	<div class="row">
		<div class="col-4 offeset-md-4">
		<h1> <span  class="badge badge-primary">{{ course.name }}</span>, <span class="badge badge-primary">{{ course.school }}</span></h1>
	</div>
	</div>
	<div class="row mt-5">
		<div class="col-4 ">
		<ul class="list-group">
			<li class="list-group-item active"> Course Notifications<h3></h3></li>
			{% for notification in notifications %}
			<li class="list-group-item"><h4>{{ notification.text }}</h4></li>
			<li class="list-group-item"><h4>{{ notification.time_stamp|date }}</h4></li>
			{% endfor %}
		</ul>
			</div>
		
	
		<div class="col-7">
			<ul class="list-group">
			{% for question in questions %}
				<li class="list-group-item active"><h3>  {{ question.title }} by <span style="color: purple">{{ question.asker }}</span></h3>
					<p>{{ question.description }}</p></li>
			
				
			{% for reply in question.replies.all %}
				<li class="list-group-item"><h4>{{ reply.text }}</h4>
				 <h5> by <span style="color: brown">{{ reply.replier }}</span> </h5> 
				 <p>Likes <span class="badge badge-primary badge-pill">{{ reply.likes }}</span></p></li>
				
			{% endfor %}
			{% endfor %}
			</ul>
		</div>

	</div>
</div>
	
{% endblock %}

education/templates/school_course_dashboard.html
{% extends 'base.html'%}
{% load education_filters %}
{% load static  %}
{% block title%}
{{course.name }} Page
{% endblock %}
{% block body %}


{% include "school_dashboard_base.html" with course=course %}

<div class="container">
	<div class="row">
		<div class="col-4 offeset-md-4">
		<h1>{{ course.name }}, {{ course.school }}</h1>
	</div>
	</div>
	<div class="row">
	<div class="col-3 mt-5">
		<div class="row" style="background-color: blue" >
		<h1>Wrtie The Code Of The Student To Take Attendance</h1>
		<form method="post" action="{% url 'edu:take_attend' course.id %}">
		    {% csrf_token %}
		    {{ form.as_p }}
		    <button type="submit" class="btn btn-danger">Take Student Attendance</button>
		</form>
	</div>
		<div class="row mt-5" style="background-color: green">
			<h1>Create New Exam</h1>
		<form method="post" action="{% url 'edu:create_exam' course.id %}">
		    {% csrf_token %}
		    {{ form2.as_p }}
		    <button type="submit" class="btn btn-danger">Create New Exam</button>
		</form>
	</div>
	</div>


<div class="col-8 mt-5 ">
<table class="table table-hover table-bordered table-rafeki">
  <thead class="thread-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Student name</th>
      <th scope="col">Code</th>
      <th scope="col">No. Attendances</th>
    </tr>
  </thead>
  <tbody>
    <span style="background-color: green">Top Student Attendance score : {{ top_attend.num_attend__max }}</span>

  	{% for student in students %}

    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ student.user.username }}</td>
      <td>{{ student.code}}</td>
    <!-- Template Tag to return the count of attendances for specific course object and student (source education_filters) !-->

      <td>{% student_attend_count student course %}</td>
    </tr>
{% endfor %}
  </tbody>
</table>
</div>
<div class="row mt-5">
{% for exam in course.exams.all %}

{{ exam.top_stud}}

<div class="col-3  mt-5">
<h6 class="mx-auto"><a href="{{ exam.get_absolute_url }}">{{exam|truncatechars:29 }}</a></h6>
<table class="table-hover table-bordered " style="border-color: green ">
  <thead>
    <tr>
      <th scope="col" s>#</th>
      <th scope="col">Student name</th>
      <th scope="col">Code</th>
      <th scope="col">Degree</th>
    </tr>
  </thead>
  <tbody>
    <!-- Template Tag to return ordered records from an exam object (source education_filters) !-->
    {% exam_records_ordered exam as records %}
  	{% for record in  records  %}
    <tr>
      <th scope="row" style="padding: 5px">{{ forloop.counter }}</th>
      <td style="padding: 5px">{{ record.student }}</td>
      <td style="padding: 5px">{{ record.student.code}}</td>
        {% if forloop.counter == 1 %}

          <td style="color: green; background-color: yellow; font-size: 120%">{{ record.student_degree }}</td>
        {% else %}
          <td style="font-size: 120%">{{ record.student_degree }}</td>
    </tr>
        {% endif %}
    {% empty %}
    <tr>
      <th scope="row">-</th>
      <td>None</td>
      <td>None</td>
      <td>None</td>
    </tr>
{% endfor %}
  </tbody>
</table>
</div>

{% endfor%}
</div>
{% endblock %}

education/templates/school_exam_dashboard.html
{% extends 'base.html'%}
{% load education_filters %}
{% block body %}
{% include "school_dashboard_base.html" with course=course %}

<div class="container">
	<div class="row">
		<div class="col-3 offset-md-4">
			<h1>{{ course.name }}, {{ course.school }}</h1>

		</div>
	</div>
	<div class="row">
<div class="col-2">
	<!-- Button trigger modal -->
	<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
	  Take Exam Degrees
	</button>

	<!-- Modal -->
	<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
					<h2>Wrtie The Code Of The Student and Degree </h2>
					<h3 style="color: white">Max degree is {{ exam.max_mark }}</h3>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <div class="modal-body">
					<form method="post" action="{% url 'edu:create_exam_record' course.id exam.id %}">
					    {% csrf_token %}
					    {{ form.as_p }}
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
	        <button type="submit" class="btn btn-danger">Submit Student Degree</button>
					</form>
	      </div>
	    </div>
	  </div>
	</div>
</div>




{% exam_records_ordered exam as records %}
		<div class="col-8 mt-5 offset-md-2">
		<table class="table table-hover table-bordered">
		  <thead>
		    <tr>
		      <th scope="col">#</th>
		      <th scope="col">Student name</th>
		      <th scope="col">Code</th>
		      <th scope="col">Degree</th>
		    </tr>
		  </thead>
		  <tbody>
		  	{% for record in records %}
		    <tr>
		      <th scope="row">{{ forloop.counter }}</th>
		      <td style="font-size: 120%">{{ record.student }}</td>
		      <td style="font-size: 120%">{{ record.student.code}}</td>

		      	{% if forloop.counter == 1 %}

					<td style="color: green; background-color: yellow; font-size: 120%">{{ record.student_degree }}</td>
				{% else %}
					<td style="font-size: 120%">{{ record.student_degree }}</td>

				{% endif %}
				{% endfor %}

		    </tr>



		</div>
		</div>
</div>

{% endblock %}

education/templates/student_all_courses_state.html
{% extends 'base.html'%}
{% load education_filters %}
{% block body%}

<div class="container">
	<div class="row ">
		<div class="col-4 mx-auto mt-5">
		<h1>Student <span class="badge badge-primary">{{ student.user.username }}</span>
			Code: <span class="badge badge-danger">{{ student.code }}</span></h1>
	</div>
	</div>

<div class="row">
<h4 class="ml-auto">الحضور ونسبة الغياب</h4>
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Exam</th>
      <th scope="col">Degree</th>
      
    </tr>
  </thead>
  <tbody>
  	{% for course in courses %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{course.name}}</td>
      {% student_attend_count student course as attend_count %}
      {% course_attend_max course as attend_max %}
      <td><span class="font-weight-bold" style="color: #dd2d41">{{ attend_count }}</span> / {{attend_max}}</td>
   
      {% precentage_calc attend_count attend_max as precentage %}
      <td><span class="font-weight-bold" style="color: #dd2d41; "> {{ precentage }}% </span></td>
    </tr>
    {% endfor %}
  </tbody>
</table>



</div>
<div class="row">
<h4 class="ml-auto">الامتحانات والاختبارات الجزئية</h4>

	<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Course</th>
      <th scope="col">Exams Degrees</th>
      <th scope="col">Precentage</th>
    </tr>
  </thead>
  <tbody>
  	{% for course in courses %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{course.name}}</td>
      {% student_course_exams_progress student course as degrees %}
    
      <td><span class="font-weight-bold" style="color: #dd2d41">{{ degrees.student }} </span>/ {{ degrees.exams }}</td>
   
      {% precentage_calc degrees.student degrees.exams as precentage %}
      <td ><span  class="font-weight-bold" style="color: #dd2d41"> {{ precentage }}% </span></td>
    </tr>
    {% endfor %}
  </tbody>
</table>

	
</div>

	


{% endblock %}

education/templates/student_course_info.html
{% extends 'base.html'%}
{% load education_filters %}
{% block body %}
<br>

<div class="mt-5" id='root'></div>
<div   class="container">
	<div class="row mt-5">
		<div class="col-4 mx-auto">
			<h1><span class="badge badge-primary">{{ course.name }}</span></h1>
			<h2>  Page OF: <span class="badge badge-primary" style="color: rgb(101,205,227);">{{ student }}</span></h2>
		</div>
	</div>
	<div class="row">
		<form method="get" class="form-control">
			{{ form.as_p }}
			<button class="btn btn-primary mb-2" type="submit">Filter Results</button>
		</form>
	</div>

	<div class="row mt-5">
		<div class="col-4">
			<ul class="list-group">
			<li class="list-group-item badge-primary"><h2>The number of times attended the course: {{ attendances.count }}</h2></li>

			{% for attendance in attendances %}
			<li class="list-group-item">{{ attendance.attend_time }}</li>


			{% endfor %}
        </ul>
		</div>



        <div class="col-5 ml-auto ">
            <h4 class="mx-auto">الامتحانات والدرجات</h4>
            <table class="table table-striped table-bordered table-hover table-inverse">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Exam</th>
                  <th scope="col">Degree</th>

                </tr>
              </thead>
              <tbody>
               {% for record in records %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{record.exam|truncatechars:60}}</td>
                    <td> <span class="font-weight-bold" style="color: #dd2d41"> {{ record.student_degree }} </span>/ {{record.exam.max_mark}} </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>


			{% student_course_exams_progress student course as exam_progress %}
			</ul>
			<div class="row mt-5" style="background-color: rgb(101,205,227); "><h4>Total student degrees <span style="color: green">{{ exam_progress.student }}</span>  out of <span style="color: red">{{ exam_progress.exams }} </span>degrees.</h4>
			<h4>Student Exam Precentage is <span style="color: green">{{ exam_progress.precentage }} %</span>.</h4></div>

			</div>

		</div>
	</div>
</div>



<div class="row mt-5">
<div class="col-5">
<canvas id="student_exam_chart" width="400" height="400"></canvas>
</div>
<div class="col-5 offset-md-1">
<canvas id="student_attendance_chart" width="400" height="400"></canvas>
</div>
</div>

<script>
var ctx = document.getElementById("student_attendance_chart").getContext('2d');
{% student_course_exams_progress student course as exam_progress %}
var mydata={{ exam_progress|safe }}
var myChart = new Chart(ctx, {
    type: 'pie',
    data: {
        labels: ['Student Degrees', 'Full Mark' ,mydata.precentage],

        datasets: [{
            label: '# of Votes',
            data: [mydata.student, mydata.exams],

            backgroundColor:['rgba(46.3, 86.3, 20.4)',
            'rgba(71.4, 7.5, 18.8)'
        ]

        }]
    }


});
</script>




<script>
var ctx = document.getElementById("student_exam_chart").getContext('2d');
{% student_chart_exams_data student.code course.pk as exam_chart_data %}
var mydata={{ exam_chart_data|safe }}
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: mydata.labels,
        datasets: [{
            label: 'Student Exam Degrees',
            data: mydata.data,
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>

{% endblock %}

education/templates/student_course_report.html
{{ report.student }}
{{ report.total_student_degrees }}
{{ report.total_max_exam_degrees }}

<h1>Hi</h1>

education/templates/take_attend.html
{% extends 'base.html'%}
{% block body %}

<form method="post" action="{% url 'edu:take_attend' course.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-danger">Take Student Attendance</button>
</form>


{% endblock %}