beta2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^pub/', include('public.urls', namespace='public')),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^', include('education.urls', namespace='edu')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

education/urls.py
from django.conf.urls import url, include
from education import school_dashboard_views as school_views
from education import student_dashboard_views as student_views
from education import views



student_urlpattern=[

    url(r'^$', student_views.StudentCourses.as_view(), name='signed_home'),
    url(r'^(?P<student_code>\w+)/$', student_views.StudentAllCoursesState.as_view(), name='student_all_courses_state'),
    url(r'^course/(?P<course_pk>\d+)/(?P<student_code>\w+)/report/', student_views.StudentCourseReport.as_view(),name='student_course_report'),
    url(r'^course/(?P<course_pk>\d+)$', student_views.CourseViewForParticipant.as_view(), name='course_dashboard_participant'),
]

school_urlpattern=[
    url(r'^course/(?P<course_pk>\d+)/add/$', school_views.AddingStudentView.as_view(), name='adding_student'),
    url(r'^course/(?P<course_pk>\d+)/exam/(?P<exam_pk>\d+)/$', school_views.SchoolExamDashboardView.as_view(), name='exam_detail'),
    url(r'^course/(?P<course_pk>\d+)/$', school_views.CourseViewForSchool.as_view(), name='course_dashboard'),



#form POST urls not GET
    url(r'^course/(?P<course_pk>\d+)/take/$', school_views.take_attend, name='take_attend'),
    url(r'^course/(?P<course_pk>\d+)/exam/create/$', school_views.create_exam, name='create_exam'),
    url(r'^course/(?P<course_pk>\d+)/exam/(?P<exam_pk>\d+)/create/$', school_views.create_exam_record, name='create_exam_record'),

#api tests not for production
    url(r'^course/(?P<course_pk>\d+)/(?P<student_code>\w+)/json/', student_views.AttendanceJsonView.as_view(),name='student_attend_json'),
    url(r'^course/(?P<student_code>\w+)/json/', student_views.StudentCoursesAttendancesJsonView.as_view(),name='student_attend_json'),

]
general_urlpattern=[
    url(r'^template/$', views.Template.as_view(), name='template'),
    url(r'^student/create/$', views.UserCreateStudentView.as_view(), name='create_student'),
    url(r'^$', views.AllCoursesList.as_view(), name='not_signed_home'),
    
    #Student Report for specific course both student , school and parents can access
    url(r'^course/(?P<course_pk>\d+)/(?P<student_code>\w+)/', views.StudentCourseInfoView.as_view(),name='student_course_info'),

]

urlpatterns= [
url(r'st/',include(student_urlpattern)),
url(r'sc/',include(school_urlpattern)),
url(r'',include(general_urlpattern)),
]

templates/base2.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
        <a class="navbar-brand" href="#">Rafeki</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarsExample09">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Public</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Education</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown09" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">City</a>
            <div class="dropdown-menu" aria-labelledby="dropdown09">
              <a class="dropdown-item" href="#">Damanhour</a>
              <a class="dropdown-item" href="#">Alexandria</a>
              <a class="dropdown-item" href="#">Cairo</a>
            </div>
          </li>
        </ul>

      </div>
    </nav>

    <nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample10" aria-controls="navbarsExample10" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample10">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">Centered nav only <span class="sr-only">(current)</span></a>
          </li>

          {% if not request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="#">الدعم</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">تسجيل</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">تسجيل الدخول</a>
          </li>
          <form class="form-inline my-2 my-md-0">
            <button class="btn btn-danger" type="submit" name="button"><svg height="20" width="20">
             <img class="svg" src="{% static 'img/search.svg'%}" style="height:20px; width:20px;"/>
            </svg></button>
            <input class="form-control" type="text" placeholder="Search" aria-label="Search">
          </form>


          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link " href="#">تسجيل الخروج</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">notifications</a>
          </li>

          <form class="form-inline my-2 my-md-0">
            <button class="btn btn-danger" type="submit" name="button"><svg height="20" width="20">
             <img class="svg" src="{% static 'img/search.svg'%}" style="height:20px; width:20px;"/>
            </svg></button>
            <input class="form-control" type="text" placeholder="Search" aria-label="Search">
          </form>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown09" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><svg height="20" width="20">
             <img class="svg" src="{% static 'img/account.svg'%}" style="height:20px; width:20px;"/>
           </svg></a>
            <div class="dropdown-menu" aria-labelledby="dropdown09">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>

          {% elif request.user.student %}
          <li class="nav-item">
            <a class="nav-link " href="#">تسجيل الخروج</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown09" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><svg height="20" width="20">
             <img class="svg" src="{% static 'img/account.svg'%}" style="height:20px; width:20px;"/>
           </svg></a>
            <div class="dropdown-menu" aria-labelledby="dropdown09">
              <a class="dropdown-item" href="{% url 'edu:signed_home'%}">Courses</a>
              <a class="dropdown-item" href="{% url 'edu:student_all_courses_state' request.user.student.pk %}">Progress</a>
              <a class="dropdown-item" href="#">Something else here</a>

            </div>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#">notifications</a>
          </li>

          <form class="form-inline my-2 my-md-0">
            <button class="btn btn-danger" type="submit" name="button"><svg height="20" width="20">
             <img class="svg" src="{% static 'img/search.svg'%}" style="height:20px; width:20px;"/>
            </svg></button>
            <input class="form-control" type="text" placeholder="Search" aria-label="Search">
          </form>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown10" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">courses</a>
            <div class="dropdown-menu" aria-labelledby="dropdown10">
              <a class="dropdown-item" href="#">{{ request.user.student.code }}</a>
              {% for course in request.user.student.courses.all %}
              <a class="dropdown-item" href="{% url 'edu:student_course_info' course.pk request.user.student.pk %}">{{ course.name }}</a>
              {% endfor %}
            </div>
          </li>

          {% endif %}
        </ul>
      </div>
    </nav>








      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </body>
</html>

templates/school_dashboard_base.html
{% load static  %}
{% block dashnavbar %}

<div class="container navbar2">
	<div class="row mt-5 mb-3">
		<div class="col-3">
			<svg class="ml-4"  height="30" width="30">
			 <img class="svg-search" src="{% static 'img/questions.svg'%}" style="height:70px; width:55px;"/>
			</svg>
			<br>
			<button class="btn-rafeki" type="button" name="questions"><a></a><h4>questions</h4></button>

		</div>
		<div class="col-3">
			<svg class="ml-2" height="30" width="30">
			 <img class="svg-search" src="{% static 'img/marks.svg'%}" style="height:70px; width:55px;"/>
			</svg>
			<br>
			<button class="btn-rafeki" type="button" name="marks"><h4>Marks</h4></button>

		</div>
		<div class="col-3">
			<svg class="ml-4" height="30" width="30">
			 <img class="svg-search" src="{% static 'img/students.svg'%}" style="height:70px; width:55px;"/>
			</svg>
			<br>
			<button class="btn-rafeki" type="button" name="students"><h4>Students</h4></button>

		</div>
		<div class="col-3">
			<svg class="ml-5"  height="30" width="30">
			 <img class="svg-search" src="{% static 'img/student.svg'%}" style="height:70px; width:55px;"/>
			</svg>
			<br>
			<button class="btn-rafeki" type="button" name="attendance"><h4>Attendance</h4></button>

		</div>
	</div>
</div>

{% endblock dashnavbar %}

{% block dashmenu %}

<div class="container">
  <div class="row mt-5">
    <div class="col-4 ml-auto">
      <form >
        <select class="custom-select" name="menu-exam" onChange="window.document.location.href=this.options[this.selectedIndex].value;" value="GO">>
        <option selected>Choose Exam</option>
        {% for exam in course.exams.all %}
            <option value="{% url 'edu:exam_detail' course_pk exam.pk %}">{{exam}}</option>
            {% empty %}
            <option value="99">You have no exams yet</option>
        {% endfor %}

      </select>
      <button type="submit" name="button">Go</button>
      </form>

    </div>

    <div class="col-4 ">
      <form>
        <select class="custom-select" name="menu-course" onChange="window.document.location.href=this.options[this.selectedIndex].value;" value="GO">>
        <option selected>Choose Course</option>
        {% for course in user.school.courses.all %}
            <option value="{% url 'edu:course_dashboard' course.pk %}">{{course.name}}</option>
            {% empty %}
            <option value="99">You have no courses</option>
        {% endfor %}

      </select>
      <button type="submit" name="button">Go</button>
      </form>

    </div>

  </div>

</div>

{% endblock dashmenu %}

templates/template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </head>
<body>
	<div class="container">
		<div class="row" style="background-image: url(https://cfe2-static.s3-us-west-2.amazonaws.com/static/assets/img/cfe-header.jpg?v=2);"></div>
	</div>
</body>
</html>